"""update users table

Revision ID: 1968083ef186
Revises: af4f1ab33f21
Create Date: 2024-09-11 23:04:43.697504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1968083ef186"
down_revision: Union[str, None] = "af4f1ab33f21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("foo", sa.Integer(), nullable=False))
    op.add_column("user", sa.Column("bar", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        op.f("uq_user_foo_bar"), "user", ["foo", "bar"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_foo_bar"), "user", type_="unique")
    op.drop_column("user", "bar")
    op.drop_column("user", "foo")
    # ### end Alembic commands ###
